Repository codeit-momentum/moment-front, pull requests merged in 2025-02, with the labels that each got.

#63 [모멘트페이지] 버킷리스트 CRUD API 연동
  src/components/Modal/CheckListModal/CheckListModal.tsx
  src/components/Modal/OKModal/OKModal.tsx
  src/components/Moment/CheckList/CheckList.tsx
  src/components/Moment/CheckList/CheckListItem/CheckListItem.tsx
  src/hooks/common/useErrorHandler.tsx
  src/hooks/queries/bucketList/useDeleteBucket.tsx
  src/hooks/queries/bucketList/useGetAchievementBucket.tsx
  src/hooks/queries/bucketList/useGetBucketDetail.tsx
  src/hooks/queries/bucketList/useGetRepeatBucket.tsx
  src/hooks/queries/bucketList/usePatchBucket.tsx
  src/hooks/queries/bucketList/usePatchBucketUpload.tsx
  src/hooks/queries/bucketList/usePostBucket.tsx
  src/pages/Moment/BucketList/BucketList.tsx
  src/pages/Moment/SelectMode.tsx
  src/pages/Moment/Upload/Upload.tsx
  src/types/moment/index.d.ts
  src/utils/moment.ts
Labels: feat, 모멘트페이지

#68 [마이페이지] 마이페이지 아이콘 수정 및 토스트 구현
  src/assets/svg/IcAddFriend.tsx
  src/assets/svg/IcArrowRight.tsx
  src/assets/svg/IcBack.tsx
  src/assets/svg/IcEditProfile.tsx
  src/assets/svg/IcGetOut.tsx
  src/assets/svg/IcLogout.tsx
  src/components/MyPage/MyMenu/MyMenu.style.ts
  src/components/MyPage/MyMenu/MyMenu.tsx
  src/components/common/.gitkeep
  src/components/common/Toast/Toast.style.ts
  src/components/common/Toast/Toast.tsx
  src/pages/MyPage/EditProfile/EditProfile.tsx
  src/pages/MyPage/Friend/Friend.tsx
  src/pages/MyPage/MyPage.tsx
Labels: feat, style, 마이페이지

#74 Feat/#49 home notice
  src/assets/svg/IcClip.tsx
  src/assets/svg/IcNotice.tsx
  src/assets/svg/IcNoticeOff.tsx
  src/components/Home/Bucketlist/Bucketlist.style.ts
  src/components/Home/Bucketlist/Bucketlist.tsx
  src/components/Home/Header/Header.style.ts
  src/components/Home/Header/Header.tsx
  src/components/Home/NotificationModal/NotificationModal.style.ts
  src/components/Home/NotificationModal/NotificationModal.tsx
  src/components/Home/TodayMomentSection/DayCheckboxGroup/DayCheckboxGroup.style.ts
  src/components/Home/TodayMomentSection/DayCheckboxGroup/DayCheckboxGroup.tsx
  src/components/Home/TodayMomentSection/MomentList/MomentList.style.ts
  src/components/Home/TodayMomentSection/MomentList/MomentList.tsx
  src/components/Home/TodayMomentSection/TodayMomentSection.style.ts
  src/components/Home/TodayMomentSection/TodayMomentSection.tsx
  src/pages/Home/Home.tsx
  yarn.lock
Labels: feat, 메인페이지

#71 [모멘트페이지] 모멘트 조회, 인증 API 연동
  src/components/Moment/CheckList/CheckListItem/CheckListItem.tsx
  src/components/Moment/ImageUpload/ImageUpload.tsx
  src/components/Moment/MomentAchievementStatus/MomentAchievementStatus.style.ts
  src/components/Moment/MomentAchievementStatus/MomentAchievementStatus.tsx
  src/components/Moment/MomentUploadStatus/MomentUploadStatus.style.ts
  src/components/Moment/MomentUploadStatus/MomentUploadStatus.tsx
  src/hooks/moment/useUpload.tsx
  src/hooks/queries/bucketList/useGetBucketDetail.tsx
  src/hooks/queries/bucketList/usePatchBucketUpload.tsx
  src/hooks/queries/moment/useGetChallengingMoment.tsx
  src/hooks/queries/moment/useGetMomentDetail.tsx
  src/hooks/queries/moment/usePatchMomentUpload.tsx
  src/pages/Moment/Moment.tsx
  src/pages/Moment/Upload/Upload.tsx
  src/types/moment/index.d.ts
  src/utils/moment.ts
Labels: feat, 모멘트페이지

#76 [공통 컴포넌트] 공통 훅 구현 및 Suspense 설정
  src/apis/client.ts
  src/components/Modal/CheckListModal/CheckListModal.style.ts
  src/components/Moment/CheckList/CheckList.style.ts
  src/components/Moment/CheckList/CheckList.tsx
  src/components/Moment/CheckList/CheckListItem/CheckListItem.tsx
  src/components/Moment/ImageUpload/ImageUpload.tsx
  src/components/Moment/MomentAchievementStatus/MomentAchievementStatus.tsx
  src/components/Moment/ToDoListComponent/ToDoListComponent.tsx
  src/components/common/Toast/Toast.style.ts
  src/hooks/common/useImageHandler.tsx
  src/hooks/common/useToast.tsx
  src/hooks/queries/bucketList/useGetAchievementBucket.tsx
  src/hooks/queries/bucketList/useGetRepeatBucket.tsx
  src/hooks/queries/moment/useGetChallengingMoment.tsx
  src/hooks/queries/useGetTodosExample.tsx
  src/pages/Moment/Moment.tsx
  src/pages/Moment/Upload/Upload.tsx
  src/pages/MyPage/EditProfile/EditProfile.tsx
  src/pages/MyPage/Friend/Friend.tsx
  src/utils/moment.ts
Labels: feat, 공통 컴포넌트

#78 [모멘트 생성페이지] 자동 모멘트 ai api 연동
  src/apis/AI/autoDuration.ts
  src/apis/AI/autoPlanning.ts
  src/apis/AI/loadExamples.ts
  src/apis/AI/planExamples.json
  src/components/Moment/CheckList/CheckListItem/CheckListItem.tsx
  src/components/Moment/DurationComponent/DurationComponent.tsx
  src/components/Moment/ToDoListComponent/ToDoListComponent.tsx
  src/hooks/common/useErrorHandler.tsx
  src/pages/BucketList/BucketList.style.ts
  src/pages/BucketList/BucketList.tsx
  src/pages/Moment/CreateMoment.tsx
  src/pages/Moment/SelectMode.tsx
  src/router/Router.tsx
  vite.config.ts
Labels: feat, 모멘트 생성페이지

#87 Develop에서 main merge (open ai 이슈 해결)
  package.json
  yarn.lock
Labels: merge

#88 [FEAT] 홈 스타일 작업, meta 태그 작업, GA 설정
  index.html
  src/assets/images/bucketAcheiveBackgroundImage.png
  src/assets/svg/IcClip.tsx
  src/assets/svg/IcLogo.tsx
  src/assets/svg/IcNotice.tsx
  src/assets/svg/IcNoticeOff.tsx
  src/assets/svg/home/IcClip.tsx
  src/assets/svg/home/IcClipOff.tsx
  src/assets/svg/home/IcSnakeLv0.tsx
  src/assets/svg/home/IcSnakeLv1.tsx
  src/assets/svg/home/IcSnakeLv2.tsx
  src/assets/svg/logo.svg
  src/components/Home/Bucketlist/Bucketlist.style.ts
  src/components/Home/Bucketlist/Bucketlist.tsx
  src/components/Home/Header/Header.style.ts
  src/components/Home/Header/Header.tsx
  src/components/Home/TodayMomentSection/DayCheckboxGroup/DayCheckboxGroup.style.ts
  src/components/Home/TodayMomentSection/DayCheckboxGroup/DayCheckboxGroup.tsx
  src/components/Home/TodayMomentSection/MomentList/MomentList.style.ts
  src/components/Home/TodayMomentSection/MomentList/MomentList.tsx
  src/components/Home/TodayMomentSection/TodayMomentSection.style.ts
  src/components/Home/TodayMomentSection/TodayMomentSection.tsx
  src/components/OnboardingSection/OnboardingSection.style.ts
  src/components/OnboardingSection/OnboardingSection.tsx
  src/pages/Home/Home.style.ts
  src/pages/Home/Home.tsx
  src/pages/Login/Login.style.ts
  src/pages/Start/Start.style.ts
  src/pages/Start/Start.tsx
Labels: feat, style, 메인페이지

#90 [모멘트 생성 페이지] FrequencyBtn 로직 및 모멘트 생성 api 연동
  src/apis/AI/autoPlanning.ts
  src/apis/mockApi.ts
  src/components/FrequenctBtn/FrequentBtn.tsx
  src/components/Moment/CheckList/CheckList.tsx
  src/components/Moment/DurationComponent/DurationComponent.tsx
  src/components/Moment/FrequencyBtnComponent/FrequencyBtnComponent.tsx
  src/hooks/queries/bucketList/usePatchBucektChallenge.tsx
  src/hooks/queries/moment/usePostMoments.tsx
  src/hooks/queries/useTodoList.tsx
  src/pages/Moment/CreateMoment.tsx
  src/pages/Moment/MomentComplete.tsx
  src/pages/Moment/SelectMode.tsx
  src/types/moment/createMomentTypes.ts
  src/utils/formatDate.ts
  src/utils/generateMomentDates.ts
Labels: feat, 모멘트 생성페이지

#93 Develop에서 main merge (모멘트 생성 추가, 마이 및 피드 QA 반영)
  src/apis/AI/autoPlanning.ts
  src/apis/mockApi.ts
  src/components/Feed/FeedItem/FeedItem.style.ts
  src/components/Feed/FeedItem/FeedItem.tsx
  src/components/Feed/FeedList/FeedList.tsx
  src/components/Feed/FriendCarousel/FriendCarousel.style.ts
  src/components/Feed/FriendCarousel/FriendCarousel.tsx
  src/components/FrequenctBtn/FrequentBtn.tsx
  src/components/Home/TodayMomentSection/TodayMomentSection.style.ts
  src/components/Modal/OKModal/OKModal.style.ts
  src/components/Moment/CheckList/CheckList.tsx
  src/components/Moment/DurationComponent/DurationComponent.tsx
  src/components/Moment/FrequencyBtnComponent/FrequencyBtnComponent.tsx
  src/components/MyPage/MyProfile/MyProfile.style.ts
  src/components/MyPage/MyProfile/MyProfile.tsx
  src/hooks/queries/Feed/useGetFeed.tsx
  src/hooks/queries/Feed/useGetFriends.tsx
  src/hooks/queries/bucketList/usePatchBucektChallenge.tsx
  src/hooks/queries/moment/usePostMoments.tsx
  src/hooks/queries/useTodoList.tsx
  src/pages/Feed/Feed.tsx
  src/pages/Moment/CreateMoment.tsx
  src/pages/Moment/MomentComplete.tsx
  src/pages/Moment/SelectMode.tsx
  src/pages/MyPage/EditProfile/EditProfile.style.ts
  src/pages/MyPage/EditProfile/EditProfile.tsx
  src/pages/MyPage/MyPage.style.ts
  src/utils/formatDate.ts
  src/utils/generateMomentDates.ts
Labels: merge

#84 Feat/#73 home api
  src/apis/client.ts
  src/assets/svg/home/IcSnakeLv0.tsx
  src/assets/svg/home/IcSnakeLv3.tsx
  src/assets/svg/home/IcSnakeLv4.tsx
  src/components/Home/Bucketlist/Bucketlist.style.ts
  src/components/Home/Bucketlist/Bucketlist.tsx
  src/components/Home/Header/Header.style.ts
  src/components/Home/Header/Header.tsx
  src/components/Home/NotificationModal/NotificationModal.tsx
  src/components/Home/TodayMomentSection/MomentList/MomentList.tsx
  src/components/Home/TodayMomentSection/TodayMomentSection.tsx
  src/hooks/queries/home/useGetBucketAchievement.tsx
  src/hooks/queries/home/useGetConsecutiveDays.tsx
  src/hooks/queries/home/useGetNotice.tsx
  src/hooks/queries/home/useGetTodayMoments.tsx
  src/hooks/queries/home/useGetWeekStatus.tsx
  src/hooks/queries/home/usePatchNotice.tsx
  src/hooks/queries/home/useWebSocketNotifications.tsx
  src/pages/Home/Home.tsx
  src/types/.gitkeep
  src/types/home/index.d.ts
Labels: bug, feat, 메인페이지

#98 [REFACTOR] 모멘트 페이지 QA 반영 및 리팩토링
  package-lock.json
  src/apis/AI/autoPlanning.ts
  src/assets/svg/IcCheckboxProcessing.tsx
  src/components/Modal/CheckListModal/CheckListModal.tsx
  src/components/Modal/SelectModal/SelectModal.style.ts
  src/components/Moment/CheckList/CheckList.tsx
  src/components/Moment/FrequencyBtnComponent/FrequencyBtnComponent.style.ts
  src/components/Moment/MomentUploadStatus/MomentUploadStatus.tsx
  src/hooks/moment/useUpload.tsx
  src/hooks/queries/bucketList/useGetBucketDetail.tsx
  src/hooks/queries/bucketList/usePatchBucketUpload.tsx
  src/hooks/queries/moment/useGetChallengingCount.tsx
  src/hooks/queries/moment/useGetChallengingMoment.tsx
  src/hooks/queries/moment/useGetMomentDetail.tsx
  src/hooks/queries/moment/usePatchMomentUpload.tsx
  src/pages/Moment/Moment.tsx
  src/pages/Moment/Upload/Upload.tsx
  src/types/moment/index.d.ts
  src/utils/generateMomentDates.ts
  src/utils/moment.ts
Labels: 모멘트페이지, refactor

#100 [Fix] 모멘트 생성 페이지 QA 반영 및 리팩토링
  package.json
  src/components/Moment/CheckList/CheckList.tsx
  src/components/Moment/ToDoListComponent/ToDoListComponent.tsx
  src/hooks/queries/bucketList/usePatchBucektChallenge.tsx
  src/hooks/useBucketId.tsx
  src/hooks/useMomentData.tsx
  src/pages/Moment/CreateMoment.tsx
  src/pages/Moment/MomentComplete.tsx
  src/pages/Moment/SelectMode.tsx
  src/utils/generateMomentDates.ts
  yarn.lock
Labels: bug, 모멘트 생성페이지, fix

#105 Develop에서 main merge (리다이렉트 설정)
  vercel.json
Labels: merge

#107 [FIX] 모멘트 생성 페이지 버그 수정 및 기타 리팩토링
  index.html
  src/apis/AI/autoDuration.ts
  src/apis/AI/autoPlanning.ts
  src/components/BackBtn/BackBtn.style.ts
  src/components/BackBtn/BackBtn.tsx
  src/components/Divider/Divider.style.ts
  src/components/Home/Bucketlist/Bucketlist.style.ts
  src/components/Home/TodayMomentSection/TodayMomentSection.style.ts
  src/components/Modal/CheckListModal/CheckListModal.tsx
  src/components/Modal/Modal.style.ts
  src/components/Moment/CheckList/CheckList.tsx
  src/components/Moment/CheckList/CheckListItem/CheckListItem.tsx
  src/components/Moment/DurationComponent/DurationComponent.style.ts
  src/components/Moment/DurationComponent/DurationComponent.tsx
  src/components/Moment/HeaderComponent/HeaderComponent.style.ts
  src/components/Moment/MomentAchievementStatus/ProgressBar.style.ts
  src/components/Moment/ToDoListComponent/ToDoListComponent.tsx
  src/components/OnboardingSection/OnboardingSection.style.ts
  src/components/OnboardingSection/OnboardingSection.tsx
  src/components/common/.gitkeep
  src/components/common/ScrollToTop/ScrollToTop.tsx
  src/components/common/Toast/Toast.style.ts
  src/layouts/Layout.tsx
  src/pages/Login/Login.tsx
  src/pages/Moment/CreateMoment.tsx
  src/pages/Moment/SelectMode.style.ts
  src/pages/Start/Start.tsx
Labels: fix

#108 [FIX] 모멘트 생성 페이지 최종확인 버튼 로직 수정
  src/assets/svg/IcConfirm.tsx
  src/assets/svg/IcEdit.tsx
  src/components/Moment/ToDoListComponent/ToDoListComponent.style.ts
  src/components/Moment/ToDoListComponent/ToDoListComponent.tsx
Labels: 모멘트 생성페이지, fix

#109 Develop에서 main merge (모멘트 생성 페이지 버그 수정)
  index.html
  src/apis/AI/autoDuration.ts
  src/apis/AI/autoPlanning.ts
  src/assets/svg/IcConfirm.tsx
  src/assets/svg/IcEdit.tsx
  src/components/BackBtn/BackBtn.style.ts
  src/components/BackBtn/BackBtn.tsx
  src/components/Divider/Divider.style.ts
  src/components/Home/Bucketlist/Bucketlist.style.ts
  src/components/Home/TodayMomentSection/TodayMomentSection.style.ts
  src/components/Modal/CheckListModal/CheckListModal.tsx
  src/components/Modal/Modal.style.ts
  src/components/Moment/CheckList/CheckList.tsx
  src/components/Moment/CheckList/CheckListItem/CheckListItem.tsx
  src/components/Moment/DurationComponent/DurationComponent.style.ts
  src/components/Moment/DurationComponent/DurationComponent.tsx
  src/components/Moment/HeaderComponent/HeaderComponent.style.ts
  src/components/Moment/MomentAchievementStatus/ProgressBar.style.ts
  src/components/Moment/ToDoListComponent/ToDoListComponent.style.ts
  src/components/Moment/ToDoListComponent/ToDoListComponent.tsx
  src/components/OnboardingSection/OnboardingSection.style.ts
  src/components/OnboardingSection/OnboardingSection.tsx
  src/components/common/.gitkeep
  src/components/common/ScrollToTop/ScrollToTop.tsx
  src/components/common/Toast/Toast.style.ts
  src/layouts/Layout.tsx
  src/pages/Login/Login.tsx
  src/pages/Moment/CreateMoment.tsx
  src/pages/Moment/SelectMode.style.ts
  src/pages/Start/Start.tsx
  vercel.json
Labels: merge

#114 [FIX] 피드페이지 및 마이페이지 2차 QA 반영
  src/App.tsx
  src/assets/svg/IcGetOut.tsx
  src/assets/svg/home/IcStamp.tsx
  src/components/Feed/FeedList/FeedList.tsx
  src/components/Home/Header/Header.tsx
  src/components/Home/TodayMomentSection/MomentList/MomentList.style.ts
  src/components/Home/TodayMomentSection/MomentList/MomentList.tsx
  src/components/Home/TodayMomentSection/TodayMomentSection.tsx
  src/components/Modal/OKModal/OKModal.tsx
  src/hooks/common/useResponseMessage.tsx
  src/hooks/queries/home/useGetConsecutiveDays.tsx
  src/hooks/queries/home/useGetTodayMoments.tsx
  src/hooks/queries/home/useGetWeekStatus.tsx
  src/hooks/queries/myPage/useDeleteAccount.tsx
  src/hooks/queries/myPage/useGetUser.tsx
  src/pages/Feed/Feed.tsx
  src/pages/Moment/Upload/Upload.tsx
  src/pages/MyPage/EditProfile/EditProfile.tsx
  src/pages/MyPage/Friend/Friend.tsx
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/NotFound/NotFound.style.ts
  src/pages/NotFound/NotFound.tsx
  src/router/Router.tsx
  src/utils/formatDate.ts
  src/utils/week.ts
Labels: 마이페이지, 피드페이지, fix

#115 [FIX] 온보딩 페이지 및 모멘트 페이지 2차 QA
  eslint.config.js
  src/assets/svg/IcDateContainer.tsx
  src/components/Divider/Divider.tsx
  src/components/FrequenctBtn/FrequentBtn.style.ts
  src/components/FrequenctBtn/FrequentBtn.tsx
  src/components/Home/TodayMomentSection/MomentList/MomentList.style.ts
  src/components/Modal/Modal.style.ts
  src/components/Modal/OKModal/OKModal.tsx
  src/components/Moment/CheckList/CheckList.style.ts
  src/components/Moment/CheckList/CheckList.tsx
  src/components/Moment/CheckList/CheckListItem/CheckListItem.tsx
  src/components/Moment/DurationComponent/DurationComponent.style.ts
  src/components/Moment/HeaderComponent/HeaderComponent.tsx
  src/components/Moment/ToDoListComponent/ToDoListComponent.style.ts
  src/components/Moment/ToDoListComponent/ToDoListComponent.tsx
  src/components/OnboardingSection/OnboardingSection.tsx
  src/components/common/Toast/Toast.style.ts
  src/hooks/common/useImageHandler.tsx
  src/hooks/common/useResponseMessage.tsx
  src/hooks/common/useToast.tsx
  src/hooks/queries/bucketList/usePatchBucektChallenge.tsx
  src/hooks/useMomentData.tsx
  src/pages/Moment/MomentComplete.style.ts
  src/pages/Moment/MomentComplete.tsx
  src/pages/MyPage/Friend/Friend.tsx
  src/pages/Start/Start.tsx
  src/utils/formatFrequency.ts
  src/utils/generateMomentDates.ts
Labels: 시작페이지, 모멘트페이지, fix

#117 Develop에서 main merge(친구 추가 문구 오류 수정)
  src/pages/MyPage/Friend/Friend.tsx
Labels: merge

#118 Develop에서 main merge (알림 조회 및 부가적인 수정 사항 반영)
  src/assets/svg/IcNotice.tsx
  src/assets/svg/IcNoticeOff.tsx
  src/assets/svg/home/IcFriendBlue.tsx
  src/assets/svg/home/IcMomentBlue.tsx
  src/assets/svg/home/IcNotice.tsx
  src/assets/svg/home/IcNoticeOff.tsx
  src/components/Home/Header/Header.tsx
  src/components/Home/NotificationModal/NotificationModal.style.ts
  src/components/Home/NotificationModal/NotificationModal.tsx
  src/components/Home/TodayMomentSection/MomentList/MomentList.tsx
  src/hooks/queries/home/useGetConsecutiveDays.tsx
  src/hooks/queries/home/useGetNotice.tsx
  src/hooks/queries/home/usePatchNotice.tsx
  src/hooks/queries/home/useWebSocketNotifications.tsx
  src/types/home/index.d.ts
  src/utils/formatFrequency.ts
  src/utils/moment.ts
Labels: merge

#121 Develop에서 main merge (리드미 배포 페이지 주소 수정)
  README.md
Labels: merge

#122 Develop에서 main merge (버킷 달성 현황 api 경로 및 리드미 백엔드 기술스택 수정)
  README.md
  src/hooks/queries/home/useGetBucketAchievement.tsx
Labels: merge

#123 Develop에서 main merge (svg 오류 해결)
  src/assets/svg/home/IcSnakeLv3.tsx
  src/assets/svg/home/IcSnakeLv4.tsx
Labels: merge
