Repository codeit-momentum/moment-front, pull requests merged in 2025-01, with the labels that each got.

#3 [초기세팅] 폴더구조 형성 및 초기설정
  README.md
  index.html
  package.json
  src/App.css
  src/App.tsx
  src/apis/.gitkeep
  src/assets/images/.gitkeep
  src/assets/svg/.gitkeep
  src/components/.gitkeep
  src/hooks/common/.gitkeep
  src/hooks/queries/.gitkeep
  src/index.css
  src/layouts/.gitkeep
  src/main.tsx
  src/pages/.gitkeep
  src/pages/Start/Start.style.ts
  src/pages/Start/Start.tsx
  src/router/.gitkeep
  src/store/.gitkeep
  src/styles/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  yarn.lock
Labels: 초기세팅

#8 [초기세팅] router, axios, react query 초기세팅
  package.json
  src/App.tsx
  src/apis/.gitkeep
  src/apis/client.ts
  src/apis/queryClient.ts
  src/hooks/queries/useGetTodosExample.tsx
  src/router/.gitkeep
  src/router/Router.tsx
  yarn.lock
Labels: 초기세팅

#10 [초기세팅] 웹앱 뷰 설정
  src/hooks/queries/.gitkeep
  src/hooks/useMobile.tsx
  src/layouts/.gitkeep
  src/layouts/Layout.tsx
  src/pages/Start/Start.tsx
  src/router/Router.tsx
Labels: 초기세팅

#14 [초기세팅] ESLint 초기설정
  eslint.config.js
  package.json
  yarn.lock
Labels: 초기세팅

#13 [초기세팅] styles 초기설정
  package.json
  src/App.tsx
  src/main.tsx
  src/styles/GlobalStyle.ts
  src/styles/mixin.ts
  yarn.lock
Labels: 초기세팅

#16 [초기세팅] Prettier 및 Husky 설정
  .gitignore
  .prettierrc
  commitlint.config.js
  eslint.config.js
  package.json
  src/App.tsx
  src/main.tsx
  src/styles/GlobalStyle.ts
  src/styles/mixin.ts
  yarn.lock
Labels: 초기세팅

#25 [초기세팅] color와 font 설정
  src/assets/fonts/NeoDunggeunmoPro-Regular.woff2
  src/styles/GlobalStyle.ts
  src/styles/theme.tsx
Labels: 초기세팅

#28 [공통컴포넌트] GNB 중첩라우팅 및 link 방식 수정
  src/components/GNB/GNB.style.ts
  src/components/GNB/GNB.tsx
  src/layouts/LayoutWithGNB.tsx
  src/router/Router.tsx
Labels: 공통 컴포넌트, fix

#27 [피드페이지] 피드페이지 뷰 구현
  package.json
  src/assets/images/mockImage.jpg
  src/assets/svg/IcAddFriend.tsx
  src/assets/svg/IcCheer.tsx
  src/components/Feed/EmptyFeed/EmptyFeed.style.ts
  src/components/Feed/EmptyFeed/EmptyFeed.tsx
  src/components/Feed/FeedItem/FeedItem.style.ts
  src/components/Feed/FeedItem/FeedItem.tsx
  src/components/Feed/FeedList/FeedList.style.ts
  src/components/Feed/FeedList/FeedList.tsx
  src/components/Feed/FriendCarousel/FriendCarousel.style.ts
  src/components/Feed/FriendCarousel/FriendCarousel.tsx
  src/components/Modal/Modal.style.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/SelectModal/SelectModal.style.ts
  src/components/Modal/SelectModal/SelectModal.tsx
  src/hooks/common/useModal.tsx
  src/hooks/useCurrentFriend.tsx
  src/pages/Feed/Feed.style.ts
  src/pages/Feed/Feed.tsx
  src/styles/GlobalStyle.ts
  src/types/feed/index.d.ts
  tsconfig.tsbuildinfo
  yarn.lock
Labels: feat, 피드페이지

#33 [초기세팅] vercel.json 추가
  vercel.json
Labels: 초기세팅, feat

#38 [스타일] 전체 배경색, padding 설정 및 GNB 아이콘 적용
  src/assets/svg/IcActiveFriends.tsx
  src/assets/svg/IcActiveHome.tsx
  src/assets/svg/IcActiveMoment.tsx
  src/assets/svg/IcActiveMyPage.tsx
  src/assets/svg/IcBack.tsx
  src/assets/svg/IcUnactiveFriends.tsx
  src/assets/svg/IcUnactiveHome.tsx
  src/assets/svg/IcUnactiveMoment.tsx
  src/assets/svg/IcUnactiveMyPage.tsx
  src/components/GNB/GNB.style.ts
  src/components/GNB/GNB.tsx
  src/styles/GlobalStyle.ts
  src/styles/theme.tsx
Labels: style

#30 [모멘트 생성페이지] 모멘트 생성 페이지 뷰 구현
  src/apis/mockApi.ts
  src/components/Moment/DurationComponent/DurationComponent.style.ts
  src/components/Moment/DurationComponent/DurationComponent.tsx
  src/components/Moment/FrequencyBtnComponent/FrequencyBtnComponent.style.ts
  src/components/Moment/FrequencyBtnComponent/FrequencyBtnComponent.tsx
  src/components/Moment/HeaderComponent/HeaderComponent.style.ts
  src/components/Moment/HeaderComponent/HeaderComponent.tsx
  src/components/Moment/LoadingSpinner/LoadingSpinner.style.ts
  src/components/Moment/LoadingSpinner/LoadingSpinner.tsx
  src/components/Moment/ToDoListComponent/ToDoListComponent.style.ts
  src/components/Moment/ToDoListComponent/ToDoListComponent.tsx
  src/hooks/queries/useTodoList.tsx
  src/hooks/useApi.ts
  src/hooks/useEditable.tsx
  src/pages/Moment/CreateMoment.style.ts
  src/pages/Moment/CreateMoment.tsx
  src/pages/Moment/MomentComplete.style.ts
  src/pages/Moment/MomentComplete.tsx
  src/pages/Moment/SelectMode.style.ts
  src/pages/Moment/SelectMode.tsx
  src/router/Router.tsx
  src/styles/CommonStyles.ts
  src/styles/GlobalStyle.ts
  src/types/modeType.ts
Labels: feat, 모멘트 생성페이지

#39 [모멘트페이지] 모멘트 인증 페이지 구현 및 UI 변경 사항 적용
  src/components/Moment/ImageUpload/ImageUpload.style.ts
  src/components/Moment/ImageUpload/ImageUpload.tsx
  src/components/Moment/MomentAchievementStatus/MomentAchievementStatus.style.ts
  src/components/Moment/MomentAchievementStatus/MomentAchievementStatus.tsx
  src/components/Moment/MomentUploadStatus/MomentUploadStatus.tsx
  src/hooks/useApi.ts
  src/pages/Moment/BucketList/BucketList.style.ts
  src/pages/Moment/BucketList/BucketList.tsx
  src/pages/Moment/Moment.style.ts
  src/pages/Moment/Upload/Upload.style.ts
  src/pages/Moment/Upload/Upload.tsx
  src/router/Router.tsx
Labels: feat, 모멘트페이지

#44 [공통컴포넌트] 버튼 제작
  src/components/Button/Button.style.ts
  src/components/Button/Button.tsx
  src/styles/theme.tsx
  src/types/styled.d.ts
Labels: feat, 공통 컴포넌트

#48 [로그인] 로그인 API 연동 및 axios instance 설정
  src/apis/client.ts
  src/components/OnboardingSection/OnboardingSection.style.ts
  src/components/OnboardingSection/OnboardingSection.tsx
  src/hooks/queries/useLogin.tsx
  src/pages/Login/Login.style.ts
  src/pages/Login/Login.tsx
  src/pages/Start/Start.style.ts
  src/pages/Start/Start.tsx
Labels: feat, 시작페이지

#53 [공통 컴포넌트] CheckList 공통 컴포넌트 구현
  src/assets/svg/IcCheckboxCompleted.tsx
  src/assets/svg/IcCheckboxPending.tsx
  src/assets/svg/IcCheckboxProcessing.tsx
  src/assets/svg/IcCloseModal.tsx
  src/components/Modal/CheckListModal/CheckListModal.style.ts
  src/components/Modal/CheckListModal/CheckListModal.tsx
  src/components/Moment/CheckList/CheckList.style.ts
  src/components/Moment/CheckList/CheckList.tsx
  src/components/Moment/CheckList/CheckListItem/CheckListItem.style.ts
  src/components/Moment/CheckList/CheckListItem/CheckListItem.tsx
  src/components/Moment/ContainerLayout/ContainerLayout.style.ts
  src/components/Moment/ContainerLayout/ContainerLayout.tsx
  src/pages/Moment/BucketList/BucketList.tsx
  src/types/moment/index.d.ts
  src/utils/moment.ts
Labels: feat, 공통 컴포넌트

#54 [모멘트페이지] 모멘트페이지 스타일 적용
  src/assets/svg/IcMomentUpload.tsx
  src/assets/svg/IcUploadPreview.tsx
  src/components/Button/Button.style.ts
  src/components/Modal/Modal.style.ts
  src/components/Modal/OKModal/OKModal.style.ts
  src/components/Modal/OKModal/OKModal.tsx
  src/components/Moment/ContainerLayout/ContainerLayout.style.ts
  src/components/Moment/ContainerLayout/ContainerLayout.tsx
  src/components/Moment/ImageUpload/ImageUpload.style.ts
  src/components/Moment/ImageUpload/ImageUpload.tsx
  src/components/Moment/MomentAchievementStatus/MomentAchievementStatus.style.ts
  src/components/Moment/MomentAchievementStatus/MomentAchievementStatus.tsx
  src/components/Moment/MomentAchievementStatus/ProgressBar.style.ts
  src/components/Moment/MomentHeader/MomentHeader.style.ts
  src/components/Moment/MomentHeader/MomentHeader.tsx
  src/components/Moment/MomentTabBar/MomentTabBar.style.ts
  src/components/Moment/MomentTabBar/MomentTabBar.tsx
  src/components/Moment/MomentUploadStatus/MomentUploadStatus.style.ts
  src/components/Moment/MomentUploadStatus/MomentUploadStatus.tsx
  src/pages/Moment/BucketList/BucketList.style.ts
  src/pages/Moment/BucketList/BucketList.tsx
  src/pages/Moment/Moment.style.ts
  src/pages/Moment/Moment.tsx
  src/pages/Moment/Upload/Upload.style.ts
  src/pages/Moment/Upload/Upload.tsx
Labels: style, 모멘트페이지

#51 [모멘트 생성페이지] 모멘트생성 컴포넌트 로직 구현 및 UI 변경사항 적용, 임시 API 로직 구현
  src/apis/createMomentApi.ts
  src/apis/mockApi.ts
  src/assets/svg/IcArrow.tsx
  src/assets/svg/IcConfirm.tsx
  src/assets/svg/IcEdit.tsx
  src/assets/svg/IcLoading.tsx
  src/components/BackBtn/BackBtn.style.ts
  src/components/BackBtn/BackBtn.tsx
  src/components/Divider/Divider.style.ts
  src/components/Divider/Divider.tsx
  src/components/FrequenctBtn/FrequentBtn.style.ts
  src/components/FrequenctBtn/FrequentBtn.tsx
  src/components/Moment/DurationComponent/DurationComponent.style.ts
  src/components/Moment/DurationComponent/DurationComponent.tsx
  src/components/Moment/FrequencyBtnComponent/FrequencyBtnComponent.style.ts
  src/components/Moment/FrequencyBtnComponent/FrequencyBtnComponent.tsx
  src/components/Moment/HeaderComponent/HeaderComponent.style.ts
  src/components/Moment/HeaderComponent/HeaderComponent.tsx
  src/components/Moment/LoadingSpinner/LoadingSpinner.style.ts
  src/components/Moment/LoadingSpinner/LoadingSpinner.tsx
  src/components/Moment/ToDoListComponent/ToDoListComponent.style.ts
  src/components/Moment/ToDoListComponent/ToDoListComponent.tsx
  src/pages/Moment/CreateMoment.style.ts
  src/pages/Moment/CreateMoment.tsx
  src/pages/Moment/MomentComplete.style.ts
  src/pages/Moment/MomentComplete.tsx
  src/pages/Moment/SelectMode.style.ts
  src/pages/Moment/SelectMode.tsx
  src/router/Router.tsx
  src/types/moment/createMomentTypes.ts
  src/types/moment/modeType.ts
Labels: feat, style, 모멘트 생성페이지

#55 [피드페이지] 스타일 적용
  src/assets/svg/IcMenu.tsx
  src/components/Feed/EmptyFeed/EmptyFeed.style.ts
  src/components/Feed/EmptyFeed/EmptyFeed.tsx
  src/components/Feed/FeedItem/FeedItem.style.ts
  src/components/Feed/FeedList/FeedList.style.ts
  src/components/Feed/FeedList/FeedList.tsx
  src/components/Feed/FriendCarousel/FriendCarousel.style.ts
  src/components/Modal/SelectModal/SelectModal.style.ts
  src/components/Modal/SelectModal/SelectModal.tsx
  src/pages/Feed/Feed.style.ts
  src/pages/Feed/Feed.tsx
Labels: style, 피드페이지

#62 [마이페이지] 유저 정보 및 친구 코드 api 구현
  src/App.tsx
  src/hooks/common/.gitkeep
  src/hooks/common/useErrorHandler.tsx
  src/hooks/queries/myPage/useGetUser.tsx
  src/hooks/queries/myPage/usePatchProfile.tsx
  src/hooks/queries/myPage/usePostCheckFriend.tsx
  src/hooks/queries/myPage/usePostFriend.tsx
  src/pages/MyPage/EditProfile/EditProfile.tsx
  src/pages/MyPage/Friend/Friend.tsx
  src/pages/MyPage/MyPage.tsx
  src/store/User/UserContext.tsx
  src/types/user/index.d.ts
Labels: feat, 마이페이지

#61 [공통 컴포넌트] ToDoList 컴포넌트에 CheckListItem 컴포넌트 적용
  package.json
  src/components/Moment/CheckList/CheckListItem/CheckListItem.tsx
  src/components/Moment/ContainerLayout/ContainerLayout.style.ts
  src/components/Moment/MomentAchievementStatus/MomentAchievementStatus.tsx
  src/components/Moment/MomentUploadStatus/MomentUploadStatus.tsx
  src/components/Moment/ToDoListComponent/ToDoListComponent.style.ts
  src/components/Moment/ToDoListComponent/ToDoListComponent.tsx
Labels: feat, 공통 컴포넌트
